### ISSUE TITLE
Power BI Desktop February update issue

### ISSUE THREAD

**Issue by lorenzoincuda** [EXASOL/powerbi-exasol#2]
Hello,

one of the clients of my firm would like to set up a direct-query connection between Microsoft Power BI and Exasol data-base. 
However, through the latest Power BI version we get the following error: 

![image](https://user-images.githubusercontent.com/36198077/35865246-4a127396-0b54-11e8-8151-8c969758372c.png)

The import connection works correctly but it's not the desired solution.

The previous Power BI version works perfectly (also the direct-query connection), however by this version you cannot edit the report which were already created by the latest version.
Here the error:
![image](https://user-images.githubusercontent.com/36198077/35865624-4c61e1c6-0b55-11e8-987a-135b1a8957a9.png)

Could anyone support me for this issue please?

Thank you in advanced and best regards,
Lorenzo

**Comment by ThomasBestfleisch** [comment]
We try to reproduce it here. Could you additionaly post the exact version number of your Power BI.

**Comment by ThomasBestfleisch** [comment]
Confirmed, can be easily reproduced:

![image](https://user-images.githubusercontent.com/13940266/35969556-8ac0cf18-0cc7-11e8-80e3-cf6acf3e122a.png)

Will let you know once we have a fix.

**Comment by lorenzoincuda** [comment]
Hi Thomas,

thank you very much!

Best regards,
Lorenzo

**Comment by ThomasBestfleisch** [comment]
Hi Lorenzo,

currently it's quite sure that this is a bug in PowerBI and not the EXASOL connector, because other connectors to other databases are affected as well:

http://community.powerbi.com/t5/Issues/Power-BI-January-release-2-54-is-not-working-when-source-is-used/idi-p/341317/label-name/show%20and%20tell

http://community.powerbi.com/t5/Desktop/We-cannot-convert-the-value-null-to-type-table/td-p/346056

Nevertheless I reported this to Microsoft. Waiting for feedback.

Best

Thomas

**Comment by lorenzoincuda** [comment]
Hi Thomas,

Thank you for the update and your support!

I will inform my client about that and I'll be waiting for the update from Microsoft.

Best regards,
Lorenzo

**Comment by ThomasBestfleisch** [comment]
Hi Lorenzo,

we could find a workaround to fix this in the Connector.

Best regards

Thomas

**Comment by lorenzoincuda** [comment]
Hi Thomas,

thank you very much for your support!

Best regards,
Lorenzo
